<div class="page-header">
    <h1>Hello, welcome to Phalcon test application made by Taras Shkodenko!</h1>
</div>

<p>You're now flying with Phalcon. Great things are about to happen!</p>

<?php

if (!empty($userName)) {
    ?><p>Wellcome back, <strong><?php echo $userName . '</strong>. <a href="/login/logout">Log Out</a>.</p>';
} else {
    echo '<p><a href="/signup">Sign up here</a> or <a href="/login">Log in</a></p>';
}
